### ISSUE TITLE
How to remove the top folder as the same inputed name

### ISSUE THREAD

**Issue by gapkukb** [Huuums/vscode-folder-templates#111]
I have tried all setting properties but not got the expect result. 

eg: when i inputed  the named 'about us' , then get the path 'about us/AboutUs/xxx.tsx' , how to ignore the top folder named 'about us/'

thank you. 

![image](https://user-images.githubusercontent.com/15757875/210176403-5e914e65-1097-427c-9cdf-78a5033a3f75.png)
![image](https://user-images.githubusercontent.com/15757875/210176415-f88bdbe3-bccc-4398-ba22-e62d2842a4ed.png)

**Comment by Huuums** [comment]
Hi @gapkukb, 

the `"omitParentDirectory": true` setting should accomplish what you want. 

I can see that you have tried to use it in your screenshot. 

If this issue persists would you please provide a small repo with your template for me so I can take a more indepth look?

Thanks.

**Comment by VyacheslavKolodrubskiy** [comment]
can i make folder pascalcase? i input custom button expect get CustomButton, is it possible?

**Comment by Huuums** [comment]
@VyacheslavKolodrubskiy 

yes that's possible. The template would look pretty much exactly like in the screenshots in the first message. Then use the omitParentDirectory setting like in my comment right before yours and it works like you want it to.

**Comment by VyacheslavKolodrubskiy** [comment]
![image](https://user-images.githubusercontent.com/68462575/210178373-e2c61c18-84ed-4848-9c9b-fbaaaf11327c.png)
![image](https://user-images.githubusercontent.com/68462575/210178408-6531ea3a-981b-47c6-81b8-448bc1454ab7.png)
![image](https://user-images.githubusercontent.com/68462575/210178418-1098152a-406d-4c19-acf4-7a8f812e259f.png)
![image](https://user-images.githubusercontent.com/68462575/210178425-7a40527a-605c-4b75-85b7-ddf629cd26fc.png)
Created without folder,  I need all the files to be in a folder and when I wrote the name of the folder so that it becomes pascalcase

**Comment by Huuums** [comment]
All the filenames inside the `structure` property need to have `<FTName | pascalcase>/` added before their actual filename/extension. 

`<FTName | pascalcase>/<FTName | pascalcase>.tsx`
`<FTName | pascalcase>/index.tsx`
...etc

the openFilesWhenDone property also needs to be updated to reflect this change. Hope that helps :)

**Comment by VyacheslavKolodrubskiy** [comment]
@Huuums 
Yes it works, thanks for the help, a very useful extension that saves time on the boring creation of folders and files, I like it

**Comment by gapkukb** [comment]
@Huuums 

Thanks for your reply , I have tried with your talked about But I am still not resolve the issue , 
There is a simple repo what I do test on it , 

https://github.com/gapkukb/fttemplate-test.git

Thanks for this plugin of vscode
