### ISSUE TITLE
Custom markup syntax

### ISSUE THREAD

**Issue by irvnriir** [Huuums/vscode-folder-templates#115]
i use [Project Templates](https://marketplace.visualstudio.com/items?itemName=cantonios.project-templates) Extension, just because it allow to customize the syntax of in-template items to be replaced by input when using the template . But its not actively maintained and miss certain features .

In case im not wrong that this extension doesn't support customization of the syntax, the issue is:
* `<${..}>` interfere with C++ Templates and some documentation syntax, and though its a low chance that this will cause an error, i don't want to ever keep this in mind .
* `[${..}]` is not even a consideration . (obviously)

Alternatively, this Extension could use a more compatible syntax .
* Here is our current setup : (items which can interfere)
	* global level and lower -- `#<<{[a-z]|[A-Z]|[0-9]|"_"} ..>>` , `#{<<..>>}` .
	* documentation level and lower -- { `<<` + [..] + `>>` } , `${<<..>>}` . (minimal level relevant for this Extension)
	* preprocessing level and lower -- `%[<<..>>]` , `%{<<..>>}` , `[<<..>>]` .
	* used in base-level languages and some are in other --
		* `$<<some, not a bracket . + [|..]>>` , `$(<<..>>)` . `@<<some, not a bracket . + [|..]>>` .
		* `%<<some, not a bracket . + [|..]>>` , `%%<<some, not a bracket . + [|..]>>` . `%<<..>>%` . `!<<..>>!` , `__<<.. + [|"__"]>>` , `<<[|"__"] + ..>>__` .
		* "(" , "{" and etc. .
	
	(all levels can interfere with each other in certain ways, its sorted just for some referencing)
* Some prominently available options :
	* `%%[<<..>>]` -- we suggest this .
	* `#[<<..>>]` -- "#" is less noticeable in certain cases, than "%" .
	* `%(<<..>>)` , `#(<<..>>)` -- we suggest against this .

[some items may be missed here]

**Comment by Huuums** [comment]
I can see your concerns but I very highly doubt that you will ever run into an issue where something that you did not want to get replaced does get replaced. 

The reason is that only very specific strings are being looked for to get replaced. 

That's [FTName] or <FTName> as well as anything that you yourself can specify inside the customVariables of the template. (i.e. if you have a customVariable named `MyCustomVariable` it would look for the very specific string `[MyCustomVariable]` or `<MyCustomVariable>` inside the files.
If you want to make extra sure you can also set the `omitFTName` option for the template to `false` and then the extension really only looks for strings that you specified in the templates customVariables yourself. 

Having said that I'm not against the idea of implementing a custom notation for users to fully customize to their liking. But I will not be able to implement this shortly because I'm really busy with other things right now.

**Comment by Huuums** [comment]
Just fixed this in #117 

Sorry, this took a while but please take a look at `folderTemplates.templateNotation` in vscode settings if you want to set this on a global scale. 

Or just add templateNotation to the ftsettings.json file if you want to customize it per template.
