### ISSUE TITLE
File stops being executable 

### ISSUE THREAD

**Issue by m4rinos** [Huuums/vscode-folder-templates#122]
Is it possible to retain the files permission attributes, specifically executable?  

Now I always have to do a `chmod +x` after creating a folder with a bash script in it.

**Comment by Huuums** [comment]
hey @m4rinos I just pushed an update which should help you. Please refer here https://github.com/Huuums/vscode-folder-templates#available-ftsettingsjson-properties (specifically `setExecutablePermission`). 

I made this to be an explicit opt-in functionality because of potential security concerns if we just made every file executable by default.

**Comment by m4rinos** [comment]
thanks! this works perfectly and thank you for your quick response!!
