### ISSUE TITLE
Suggestion - change name

### ISSUE THREAD

**Issue by ofir130** [Huuums/vscode-folder-templates#36]
FFS is a known abbreviation that doesn't look good.
I also think that the explorer context commands should not state the extension name - they should integrate seamlessly.

**Comment by Huuums** [comment]
Thanks for reaching out!

You have a point with the explorer context. I will remove the extension name there and make the titles more clear in other ways with the next update. That might still be some time away because I'm busy with other stuff right now.

I also thought about renaming the extension before but I fear that it might confuse already existing users and it would entail some breaking changes like the <FFSName> placeholder no longer working. Unless I keep supporting it even after the renaming. 

I will keep it in the back of my head and I'm open to hear from others what they think about changing the name.

**Comment by Brydom** [comment]
I feel like it would be good to add something with "template", or a spin off on the word. I mean, even going plain english with something like `vscode-folder-file-templates` would explain well regarding what it does, albeit boring :)
