### ISSUE TITLE
Can't make it work, am I missing something?

### ISSUE THREAD

**Issue by afmeirelles** [Huuums/vscode-folder-templates#56]
HI, thank you so much for taking the time to build this super useful extension. I still couldn't get it to work though.

I created a .fttemplates folder in my project root and added the folder structure but when I select "Create New Templated Folder" in the context menu or via `Ctrl + Shift + p` I always get a "No configured Folder Templates found!" error.

What am I missing? Here's the repo in case you want do check it: https://github.com/onepercentio/IATE-nodejs-boilerplate

Thanks again for your time!

**Comment by Huuums** [comment]
Moin @afmeirelles ,  

thanks for reaching out. 

When I cloned your repo and tried to use the template it seemed to work fine for me. 

Could it be that you had multiple workspaces open? I don't know if the extension can handle this yet. I might have to take another look into this. Or maybe you opened the project a level up too high so that the `.fttemplates` folder wasn't at the root of the vscode project?

However I noticed a few other things. 
- The first level of children in the `.fttemplates` Folder is supposed to be the `name` of the template and inside this folder you place the actual template structure. This is so you can choose the template you want to use based on its name (if you have more than one template in a project). 
- You seem to not want to use the [FTName] but instead want to use a [ResourceName] placeholder instead. For this you have to specify the "omitFTName" and "omitParentDirectory" properties in the `.ftsettings.json` file.

Given this feedback I would suggest the following structure in `.fttemplates`
```
.fttemplates
- Default
  - .ftsettings.json
  - [ResourceName]
     - ....all the files in the ResourceNameFolder
```

.ftsettings.json content
```
{
  "customVariables": ["ResourceName"],
  "omitParentDirectory": true,
  "omitFTName": true
} 
```

I adapted these changes into this fork of your repo, feel free to take a look: https://github.com/Huuums/IATE-nodejs-boilerplate

If you have any further questions I'm happy to answer them.

**Comment by afmeirelles** [comment]
Hey, @Huuums, thanks for replying so fast. 

Your guess was right, my workspace has several projects and when I opened up another window with only one project (the boilerplate) everything worked as expected. It seem the extension doesn't cope well with multiple projects then.

I replicated some of the changes you suggested, no need for custom placeholders.

If you could make it work with a multi-project workspece that would be awesome. As you should have noticed, I'm building a reference project and it'd be really nice to allow people creating resources with just one click.

Thanks!

**Comment by Huuums** [comment]
I will definitely take a look into supporting multiproject workspaces. I will probably take a look over the weekend but can't, make any promises regarding the timeline for a fix.
