### ISSUE TITLE
How to set a transformer on a parent directory?

### ISSUE THREAD

**Issue by Luckey-Elijah** [Huuums/vscode-folder-templates#74]
I have the following Template in `.vscode/.fttemplates`:

Template: `Feature Document`

`[FTName | snakecase].md`
```md
# <FTName | capitalcase> Feature

...
```

When I generate the template, how to I make the enclosing folder use a snake case transformer?

For example The file generated is:
```txt
.
└── Some Test/
   └── some_test.md
```

When I want

```
.
└── some_test/
   └── some_test.md
```

How can I achieve this?

**Comment by Huuums** [comment]
Hey. Right now there is no way to transform the "Default parent directory".

However you can hack around a bit by creating a structure like this 

![image](https://user-images.githubusercontent.com/9745322/140091511-18bc4d9b-282c-4796-a3fa-af2284a0b319.png)

and the .ftsettings.json should look like this 
```json
{
  "omitParentDirectory": true
}
```

If you do this you essentially created your own "parent directory" and can transform it however you like.

If that's not what you are looking for feel free to ask more questions. Otherwise you can close the Issue.

**Comment by Luckey-Elijah** [comment]
This is perfect, thank you!
